---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dr-prometheus
  labels:
    app: dr-prometheus
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce       # required ReadWriteOnce ReadWriteMany
  persistentVolumeReclaimPolicy: Retain    #Recycle Retain 
  nfs:
    server: 127.0.0.1
    path: /opt/nfsserver

---
#kind: PersistentVolumeClaim
#apiVersion: v1
#metadata:
#  name: dr-prometheus
#  namespace: monitoring
#spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 50Gi
